---

- name: Install net-tools Ubuntu
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - net-tools
    - iproute2
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install net-tools RHEL
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
    - net-tools
    - iproute
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Run startup.sh
  command: './k8s_manifests/startup.sh'
  args:
    chdir: "{{ devstack_dir }}"
  environment:
    CONTRAIL_REGISTRY: "{{ contrail_docker_registry }}"
    CONTRAIL_CONTAINER_TAG: "{{ container_tag }}"
    # CONTROLLER_NODES: "{{ hostvars[groups['control-plane'][0]].ansible_default_ipv4.address }}"
    # AGENT_NODES: "{{ hostvars[groups['control-plane'][0]].ansible_default_ipv4.address }}"

