---
- name: DBG1
  debug:
    msg: "zuul: {{ zuul }}"

- name: DBG2
  debug:
    msg: "release_type: {{ release_type }}"

- name: DBG3
  debug:
    msg: "build_number: {{ build_number | default(omit) }}"

- name: DBG4
  debug:
    msg: "openstack_version: {{ openstack_version | default(omit) }}"

- name: Load contrail packaging variables
  contrail_packaging:
    zuul: "{{ zuul }}"
    release_type: "{{ release_type }}"
    build_number: "{{ build_number | default(omit) }}"
    openstack_version: "{{ openstack_version | default(omit) }}"
  delegate_to: localhost

- name: DBG packaging
  debug:
    var: packaging

- name: Return contrail_packaging variable back to zuul
  zuul_return:
    data:
      contrail_packaging: "{{ packaging }}"
  delegate_to: localhost

