---

- name: Reload ansible facts
  setup:

- name: detect default iface (with 'lower' name)
  set_fact:
    default_iface: "{{ hostvars[inventory_hostname]['ansible_interfaces'] | sort | first }}"

# use ansible_distribution for better control instead of ansible_os_family
- name: Configure interfaces
  include: "setup_interface_{{ ansible_distribution }}.yaml"
  with_items:
    - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"
  when:
    - hostvars[inventory_hostname]['ansible_' + item]['type'] == 'ether'

- name: reset | Restart network
  service:
    name: >-
      {% if ansible_os_family == "RedHat" -%}
      network
      {%- elif ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic" -%}
      systemd-networkd
      {%- elif ansible_os_family == "Debian" -%}
      networking
      {%- endif %}
    state: restarted
  become: yes

- name: Reload ansible facts
  setup:
