max_security_threshold: "7.0"
reports_dir: /tmp/scan_reports
aquascan_version: 4.2

contrail_version: >-
  {% if ansible_distribution == 'RedHat' %}
  {% set containers_tag_prefix = 'rhel-' %}
  {% endif %}
  {%- if zuul.change is defined -%}
    {{ containers_tag_prefix | default('') }}{{ zuul.change }}-{{ zuul.patchset }}
  {%- else -%}
    {{ containers_tag_prefix | default('') }}{{ packaging.docker_version }}
  {%- endif -%}
