---

- name: Check whether contrail log dir exists
  stat:
    path: '{{ contrail_log_dir }}'
  register: contrail_logdir
  become: true

- name: Gather contrail-status output
  command: "contrail-status"
  become: true
  register: cs
  ignore_errors: true

- name: Gather docker ps output
  command: "docker ps -a"
  become: true
  register: dps
  ignore_errors: true

- name: fetch contrail logs
  when: contrail_logdir.stat.isdir is defined and contrail_logdir.stat.isdir
  block:
    - name: create the contrail logs dir on executor
      file:
        path: '{{ zuul.executor.log_root }}/contrail-logs'
        state: 'directory'
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Write contrail-status output
      delegate_to: localhost
      copy:
        content: "{{ cs.stdout }}"
        dest: "{{ zuul.executor.log_root }}/contrail-logs/contrail-status.{{ inventory_hostname }}.txt"
      ignore_errors: true

    - name: Write docekr ps output
      delegate_to: localhost
      copy:
        content: "{{ dps.stdout }}"
        dest: "{{ zuul.executor.log_root }}/contrail-logs/docker-ps.{{ inventory_hostname }}.txt"
      ignore_errors: true

    - name: fetch contrail logs
      synchronize:
        src: '{{ contrail_log_dir }}/'
        dest: '{{ zuul.executor.log_root }}/contrail-logs/{{ inventory_hostname }}'
        mode: 'pull'
        recursive: yes
      become: true
      ignore_errors: true

