---

working_dir: '{{ ansible_env.HOME }}'
devstack_dir: '{{ ansible_env.HOME }}/{{ zuul.projects | selectattr("short_name", "equalto", "tf-devstack") | map(attribute="src_dir") | list | first }}'
tf_test_dir: '{{ ansible_env.HOME }}/{{ zuul.projects | selectattr("short_name", "equalto", "tf-test") | map(attribute="src_dir") | list | first }}'

contrail_docker_registry: "{{ nexus.fqdn }}:{{ nexus.registry.tungsten_ci }}"

contrail_version: >-
  {%- if zuul.change is defined -%}
    {{ zuul.change }}-{{ zuul.patchset }}
  {%- else -%}
    {{ packaging.docker_version }}
  {%- endif -%}
container_tag_suffix: >-
  {% if ansible_distribution == 'RedHat' %}
    -rhel
  {% endif %}
container_tag: "{{ contrail_version}}{{ container_tag_suffix }}"
